# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adam_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x64\x61m_manager.proto\x12\x0c\x61\x64\x61m_manager\"<\n\x0e\x43ommandRequest\x12*\n\x06motors\x18\x01 \x03(\x0b\x32\x1a.adam_manager.MotorCommand\"B\n\x0cMotorCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rgoal_position\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\"\x0e\n\x0c\x45mptyRequest\"\x0f\n\rEmptyResponse\"@\n\x0bMoveRequest\x12\x17\n\x0flinear_velocity\x18\x01 \x03(\x02\x12\x18\n\x10\x61ngular_velocity\x18\x02 \x01(\x02\x32\xf2\x01\n\x12\x41\x64\x61mManagerService\x12J\n\rHandleCommand\x12\x1c.adam_manager.CommandRequest\x1a\x1b.adam_manager.EmptyResponse\x12P\n\x15ReturnToStartPosition\x12\x1a.adam_manager.EmptyRequest\x1a\x1b.adam_manager.EmptyResponse\x12>\n\x04Move\x12\x19.adam_manager.MoveRequest\x1a\x1b.adam_manager.EmptyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adam_manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMANDREQUEST']._serialized_start=36
  _globals['_COMMANDREQUEST']._serialized_end=96
  _globals['_MOTORCOMMAND']._serialized_start=98
  _globals['_MOTORCOMMAND']._serialized_end=164
  _globals['_EMPTYREQUEST']._serialized_start=166
  _globals['_EMPTYREQUEST']._serialized_end=180
  _globals['_EMPTYRESPONSE']._serialized_start=182
  _globals['_EMPTYRESPONSE']._serialized_end=197
  _globals['_MOVEREQUEST']._serialized_start=199
  _globals['_MOVEREQUEST']._serialized_end=263
  _globals['_ADAMMANAGERSERVICE']._serialized_start=266
  _globals['_ADAMMANAGERSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
