# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import adam_manager_pb2 as adam__manager__pb2


class AdamManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleCommand = channel.unary_unary(
                '/adam_manager.AdamManagerService/HandleCommand',
                request_serializer=adam__manager__pb2.CommandRequest.SerializeToString,
                response_deserializer=adam__manager__pb2.EmptyResponse.FromString,
                )
        self.ReturnToStartPosition = channel.unary_unary(
                '/adam_manager.AdamManagerService/ReturnToStartPosition',
                request_serializer=adam__manager__pb2.EmptyRequest.SerializeToString,
                response_deserializer=adam__manager__pb2.EmptyResponse.FromString,
                )
        self.Move = channel.unary_unary(
                '/adam_manager.AdamManagerService/Move',
                request_serializer=adam__manager__pb2.MoveRequest.SerializeToString,
                response_deserializer=adam__manager__pb2.EmptyResponse.FromString,
                )


class AdamManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnToStartPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdamManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleCommand,
                    request_deserializer=adam__manager__pb2.CommandRequest.FromString,
                    response_serializer=adam__manager__pb2.EmptyResponse.SerializeToString,
            ),
            'ReturnToStartPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnToStartPosition,
                    request_deserializer=adam__manager__pb2.EmptyRequest.FromString,
                    response_serializer=adam__manager__pb2.EmptyResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=adam__manager__pb2.MoveRequest.FromString,
                    response_serializer=adam__manager__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adam_manager.AdamManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdamManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adam_manager.AdamManagerService/HandleCommand',
            adam__manager__pb2.CommandRequest.SerializeToString,
            adam__manager__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReturnToStartPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adam_manager.AdamManagerService/ReturnToStartPosition',
            adam__manager__pb2.EmptyRequest.SerializeToString,
            adam__manager__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adam_manager.AdamManagerService/Move',
            adam__manager__pb2.MoveRequest.SerializeToString,
            adam__manager__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
